### ISSUE TITLE
How to provide the vertical space between the signIn buttons.

### ISSUE THREAD

**Issue by SwarnaKishore** [meteor-useraccounts/materialize#11]
I am using useraccounts materialize for my meteor project. Everything works fine, except the vertical space between the signIn buttons. I used {{> atNavButton }}  for the display. The following screen shot shows that there is no space between the buttons. Is there any way that I can provide the vertical space between the buttons without them sticking to each other? 

![screen shot 2015-04-26 at 11 38 07 am](https://cloud.githubusercontent.com/assets/7230788/7338157/d57675ea-ec08-11e4-9919-a1a1afd998b1.png)

**Comment by splendido** [comment]
I think something changed with the latest version of materialize.
If you check the deployed boilerplate at [useraccounts-materialize.meteor.com/](http://useraccounts-materialize.meteor.com/) you'll see there's still a bottom margin of 15px.

To put it back some simple CSS rule like this one

``` CSS
.at-social-btn {
   margin-bottom: 15px;
 }
```

is enough.

**Comment by SwarnaKishore** [comment]
Hi @splendido,

Thanks for the reply. It works fine now. Sorry for the simple question, I would have solved it.
