### ISSUE TITLE
div wrapper styles in full_page_at_form.html

### ISSUE THREAD

**Issue by rvzzz** [meteor-useraccounts/materialize#12]
Hi,
First of all thank you for this awesome package, I'm a beginner in the meteor world ( or webdev in general) and never felt so excited in learning a web technology.
I'm trying to create a login page to suit mobile screen sizes, and I noticed that on my tablet the size of the buttons don't fit quite well and I searched in the repo and came to the conclusion that's because the wrapper div inline styles inside the `full_page_at_form.html` file.

```
<div class="row">
    <div class="col s12 m8 offset-m2 l4 offset-l4 z-depth-1">
        {{> at_form}}
    </div>
 </div>
```

![screen shot 2015-07-01 at 07 04 33](https://cloud.githubusercontent.com/assets/3394457/8448446/8e31d554-1fbf-11e5-9c61-f55c8bb047f2.png)

I would like to have bigger sizes for medium and larger, but I can't see how to achieve this..

Is there a way to change these styles inside the `AccountsTemplates.configure` object?
Or perhaps it would be better to add an id to this div to let us define styles that precede in css importance, idk..
what's the best solution? thank you in advance

**Comment by splendido** [comment]
Hi @rvnerd.
I'm sorry for the late reply. I've been away from home for a long time...

If you think everyone would benefit from bigger sizes, please feel free to play a little with them and submit a Pull Request to change the code (or simply state the better values and I'll change them).

Differently, you could define your own version of `fullPageAtForm` template and instruct AT to use yours in place of the default one: see the `template` parameter in the [Routing](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#routing) section of the guide.

**Comment by 100ideas** [comment]
I want to customize the default template too... just add a couple specific classes etc.
