### ISSUE TITLE
Any reason for the iron:router dependency? 

### ISSUE THREAD

**Issue by lsunsi** [meteor-useraccounts/materialize#13]
I'm just asking because usually I prefer using FlowRouter for my projects.

**Comment by Falieson** [comment]
+1 (also, I've found this fork though don't know its status: https://github.com/PhilippSpo/useraccounts-materialize-flow )

**Comment by Falieson** [comment]
+1

**Comment by splendido** [comment]
Hi all,
I was not aware of the above linked fork.
What I know is @PhilippSpo is the guy behind the [flow-router-integration](https://github.com/meteor-useraccounts/core/tree/flow-router-integration) branch of useraccounts.
So I think he could shade some light on this.

I hope to get back to v2.0 asap, and `iron:router` will not be a dependency animore!
...my mind still have to _actually get back_ from my long vacation... :-)

**Comment by Falieson** [comment]
@splendido I look forward to the new release! the IR dependency has definitely caused me issues. I linked that fork from @PhilippSpo but I'm not sure how to use it in my own project or to move forward with materialize useraccounts and flow-router?

**Comment by PhilippSpo** [comment]
@Falieson look here for the most recent [discussions](https://github.com/meteor-useraccounts/core/issues/308)

**Comment by splendido** [comment]
Closing this, because I'm about to publish new versions without no routing support in core.

**Comment by dandv** [comment]
@lsunsi: out of curiosity, where did you see the iron:router dependency? `package.js` has never had it. Maybe in useraccounts:core, or in the boilerplate, and you filed the issue here instead for some reason?
