### ISSUE TITLE
Custom Button Class

### ISSUE THREAD

**Issue by scottmcpherson** [meteor-useraccounts/materialize#16]
Hey @splendido, would it be cool to add the at buttons class as a parameter to the template so that we're not stuck with that default teal? I would be happy to submit the PR, but I believe this is all it would take:

```
<template name="atNavButton">
  <a id="at-nav-button" class="waves-effect btn-flat {{class}}">{{text}}</a>
</template>
```

**Comment by splendido** [comment]
this kind of class configurations will be included with v2.0.
For now you can redefine your template with:

``` html
<template name="myAtNavButton">
  <a id="at-nav-button" class="waves-effect btn-flat red">{{text}}</a>
</template>
```

``` javascript
Template.myAtNavButton.replaces("atNavButton");
```

See [this comment](https://github.com/meteor-useraccounts/core/issues/366#issuecomment-96380408) to get more details.
