### ISSUE TITLE
Passwords always don't match

### ISSUE THREAD

**Issue by ksendra** [meteor-useraccounts/materialize#17]
Hi, I have a problem with the sign-up form with materialize template. 
I have added an additional element to the form - "user type" dropdown. When I enter identical passwords and click to select dropdown (or click away from password fields) - I get "Passwords don't match" error and register button grays out. But I still can click the register button and it sign me up successfully. Is this a bug or am I doing something wrong?

EDIT: This only happens when signup form is in a modal.

![passwordsdontmatch](https://cloud.githubusercontent.com/assets/5622744/9935427/3743d93a-5d5f-11e5-910b-f43eabca4f94.JPG)

**Comment by splendido** [comment]
tracking this on https://github.com/meteor-useraccounts/core/issues/188
