### ISSUE TITLE
forbidClientAccountCreation set to true has very little space on the bottom

### ISSUE THREAD

**Issue by mitar** [meteor-useraccounts/materialize#19]
![screen shot 2015-10-19 at 9 46 30 pm](https://cloud.githubusercontent.com/assets/585279/10598119/e27d96f6-76aa-11e5-92ce-44ebee4cefe6.png)

**Comment by splendido** [comment]
Yeah, I guess this should be fixed with some more love for the CSS rules! :-(

...perhaps the same love that [Orange](http://orange.biolab.si/) got during its amazing development? ;-)

**Comment by mitar** [comment]
Is this invitation for a pull request? ;-)

You can just give me commit access. ;-)

**Comment by splendido** [comment]
No, well I wanted to somehow mention Orange because I've discovered only a few days ago you've been probably involved with it, that's it.

Btw, if you'd like to jump on the boat I have no problem adding you to the [materialize team](https://github.com/orgs/meteor-useraccounts/teams/materialize) ;-)

**Comment by mitar** [comment]
> No, well I wanted to somehow mention Orange because I've discovered only a few days ago you've been probably involved with it, that's it.

Yea. :-) I have been involved in never released web version of it. Sadly, I had to do it before Meteor. So a lot of reactivity stuff I had to do myself.

> Btw, if you'd like to jump on the boat I have no problem adding you to the materialize team ;-)

Great! I will now just have to resist the temptation to rewrite the whole thing into Blaze Components. ;-)

**Comment by splendido** [comment]
I still had no time to check-out Blaze Components but if you think it's worth to considering them for version 2.0 (which I'm still, slowly, very slowly :( working on...) I'd like to have a chat about it!

If you write me an email I'd like to invite you on the useraccounts' slack channel if that's fine with you

**Comment by mitar** [comment]
I think for such modular system and something which should be extensible Blaze Components are definitely the way to go. At least this is what they were designed to do. But of course I am biased. And I also do not have time to do much myself (just maintaining core library is enough for me).

**Comment by splendido** [comment]
not the top solution, but should be much better now...
