### ISSUE TITLE
package name

### ISSUE THREAD

**Issue by splendido** [meteor-useraccounts/materialize#2]
What do you think @meteor-useraccounts/materialize?
1. useraccounts:materialize
2. useraccounts:materialize-css
3. useraccounts:materialize.css (although I'm not a fan of dots within packages' name...)

**Comment by Sivli-Embir** [comment]
Looking at their website it seems the CSS bit is just namespacing for the web. I vote useraccounts:materialize.

**Comment by sireskay** [comment]
I vote useraccounts:materialize as well. Thanks guys for all you are doing for the community.

**Comment by splendido** [comment]
:+1:
