### ISSUE TITLE
Forgot password leads to unstyled box

### ISSUE THREAD

**Issue by mlecoq** [meteor-useraccounts/materialize#21]
Hi,

I am making some tests with materialize ui. 

When a click on "forgot password?" link, I receive a mail containing a link to reset it.

```
Hello,

To reset your password, simply click the link below.

http://localhost:3000/#/reset-password/7sfaX2E9M9IasQVq02Ofb2jgIRtzsxBvj2YR_6MvR-9

Thanks.
```

When I click on the link, an unstyled popup is displayed : 

![sans titre](https://cloud.githubusercontent.com/assets/3649784/12269193/744cc0d8-b950-11e5-8f7d-ae6e6bf5d298.png)

Am I missing something ? All other forms are well displayed.

Thanks,
Mickael

**Comment by mitar** [comment]
Yes. That URL is not correct. Have you configured `AccountsTemplates.configureRoute('resetPwd', ...)`?

**Comment by mitar** [comment]
(In other words: I cannot reproduce this and it works for me.)

**Comment by mlecoq** [comment]
@mitar Have you tried to reset a password ? The popup is displayed but it is not materialized

**Comment by mitar** [comment]
Yes I did. Resetting password works for me and when I click on a link in the e-mail I get a normal Materialize form. I have tested it [in this app](https://github.com/peer/mind).

**Comment by mlecoq** [comment]
In your example, you have created your own template. When you do not configure _resetPwd_ route, you have a default behavior with a popup. 

I have overridden the popup: 

resetPasswordDialog.html :

    <template name="resetPasswordDialog">
      {{#if inResetPasswordFlow}}
       <div class="hide-background"></div>
         <div class="accounts-dialog accounts-centered-dialog">
      <label id="reset-password-new-password-label" for="reset-password-new-password">
       New Password
      </label>

      <div class="reset-password-new-password-wrapper">
        <input id="reset-password-new-password" type="password">
      </div>

      <div class="login-button login-button-form-submit" id="login-buttons-reset-password-button">
       Modify your password
      </div>

         <a class="accounts-close" id="login-buttons-cancel-reset-password">×</a>
      </div>
     {{/if}}
    </template>




resetPasswordDialog.js


    import { Template } from 'meteor/templating'; 
    import './resetPasswordDialog.html';

    Template.resetPasswordDialog.replaces('_resetPasswordDialog'); 
    Template.resetPasswordDialog.inheritsHelpersFrom('_resetPasswordDialog');
    Template.resetPasswordDialog.inheritsEventsFrom('_resetPasswordDialog');
