### ISSUE TITLE
How do you change the button's waves-effect color?

### ISSUE THREAD

**Issue by lukastheiler** [meteor-useraccounts/materialize#22]
Hi, 

I think 
`{{> atNavButton }}`
 currently uses .waves-teal . I can change the button colors via css: 

```
.btn, .btn-large { 
  background-color: #455A64; /* BG */
  color: #CFD8DC; /* Text */
}
```

But how can i change the waves effect color? 

Thanks! Lukas

**Comment by mitar** [comment]
I think this is a better question for Materialize CSS repository.
