### ISSUE TITLE
Check new button style

### ISSUE THREAD

**Issue by splendido** [meteor-useraccounts/materialize#3]
I've just made all buttons full width.
See 06ec396fc71f00f8171c937d570f0b23468ec8ea

What do you think about this?

**Comment by Sivli-Embir** [comment]
This is much better, thank for that! Any chance you could publish this now?

**Comment by splendido** [comment]
Hi Silvi, 
It's gettin very late here, I'm sorry I can't :(
Would it be fine if I do it in one or two days?

**Comment by Sivli-Embir** [comment]
Yep that's fine. I will be back Sunday/Monday, thanks!
