### ISSUE TITLE
Username setting doesn't seem to be applied

### ISSUE THREAD

**Issue by Cypher1** [meteor-useraccounts/materialize#30]
Settings from my imports/startup/accounts-config.js

```
import { Accounts } from 'meteor/accounts-base';

Accounts.ui.config({
    passwordSignupFields: 'USERNAME_AND_EMAIL',
});
```

**Comment by yoonwaiyan** [comment]
Have you tried the "Login with Username or Email" section as mentioned in the Guide README?

**Comment by Cypher1** [comment]
This is not for sign in (or log in depending on your preferred terminology)
but for sign up.

I've worked around it using the  AccountTemplates.remove hack but it's
annoying that the option from Accounts is ignored by AccountsTemplates.

Thanks
