### ISSUE TITLE
Improve link location and add _uihook animations?

### ISSUE THREAD

**Issue by Sivli-Embir** [meteor-useraccounts/materialize#4]
@splendido we have talked about this a little already.

First I think the links should be in the same spot: (Sorry using custom T9n es, en is broken)
![my_bus_app](https://cloud.githubusercontent.com/assets/1283884/6156634/b3bae74e-b209-11e4-9f4e-a05e3e17bada.png)
![my_bus_app](https://cloud.githubusercontent.com/assets/1283884/6156658/e8cb284a-b209-11e4-84be-a8a96a4b87bb.png)

Second when you click on "Necesita una nueva contraseña?" The password should fade out and the button and link should slide up. Maybe this will not be the default but there should be a way to easily plug animations.

Thoughts? From anyone.

**Comment by Sivli-Embir** [comment]
Actually I probably should have put that in core, sorry was not thinking. @splendido do you want this moved?

**Comment by splendido** [comment]
Yes please, move this to core!

Tnx!

**Comment by splendido** [comment]
Closing this one, but waiting for the same on core!

Tnx!

**Comment by Sivli-Embir** [comment]
Ah sorry, long day... week... month... anyway [moved](https://github.com/meteor-useraccounts/core/issues/282) thanks!
