### ISSUE TITLE
How to use this correctly?

### ISSUE THREAD

**Issue by Exegetech** [meteor-useraccounts/materialize#5]
Hello,

Sorry for my stupid question.  But I am trying to use useraccounts materialize and wondering how to achieve the look that the example gives
![screen shot 2015-03-09 at 14 23 55](https://cloud.githubusercontent.com/assets/7025139/6561481/f2be7dee-c667-11e4-8061-8844bb60df0d.png)

What I got when putting {{> atForm}} is this picture
![screen shot 2015-03-09 at 14 21 05](https://cloud.githubusercontent.com/assets/7025139/6561465/e060439e-c667-11e4-86ea-86402e3a1d86.png)

Sorry for my stupid question

**Comment by splendido** [comment]
Hello @christiansakai,
for a quick start you can have a look at the [boilerplates](https://github.com/meteor-useraccounts/boilerplates).

From what I can see you should add at least an account service with `meteor add accounts-password` or some social login service. Lets have a look at the [Setup](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#setup) section of the [Guide](https://github.com/meteor-useraccounts/core/blob/master/Guide.md)

you also have to add your materialize package ;-)

**Comment by Exegetech** [comment]
Hi @splendido,

Thanks for the reply.  Yes I git clone all the boilerplate, but it seems there is no structure inside that actually defines it.  I might have missed it.

I already add `meteor add accounts-password` and also `meteor add materialize:materialize` but still can't figure out how to actually use it.

So, seems like I am missing the entire part where "sign up with google" and "username and password" field is.  I only get the h1 "Sign up" and p "don't have an account? register"

**Comment by splendido** [comment]
So the [materialize](https://github.com/meteor-useraccounts/boilerplates/tree/master/materialize) boilerplate didn't work for you?
it's deployed [here](https://github.com/meteor-useraccounts/boilerplates)

It should be enough to add some accounts packages (as you already did) run meteor update to get all packages installed and up to date.
Make sure you have [at condifuration file](https://github.com/meteor-useraccounts/boilerplates/blob/master/materialize/lib/config/at_config.js) and [accounts configuration file](https://github.com/meteor-useraccounts/boilerplates/blob/master/materialize/server/lib/config/accounts.js) and that should be it!

Let me know!

**Comment by Exegetech** [comment]
Thank you.  I will look into it more

**Comment by der-daniel** [comment]
Links are not working.
Stuck at the same problem..
