### ISSUE TITLE
"OR" text under accounts-* buttons is not properly center aligned

### ISSUE THREAD

**Issue by asidiali** [meteor-useraccounts/materialize#6]
```
<div class="at-sep row">
  <div class="col s1 offset-s5">
    <strong>OR</strong>
  </div>
</div>
```

Does not center the text horizontally within the parent container. Maybe something like:

`<div class="col s6 offset-s3">`

with centered text?

**Comment by asidiali** [comment]
I tried to recreate a small sample with MeteorPad but for some reason I was unable to add useraccounts:core to the project without it crashing.

**Comment by Sivli-Embir** [comment]
I tried to center it when I first drafted this package but I never could get it to look right. If can get it to work this has my vote. Not sure about the MeteorPad but you can fork https://github.com/meteor-useraccounts/boilerplates to try out changes.

**Comment by asidiali** [comment]
The change is needed in /lib/at_sep.html:

```
<template name="atSep">
  <div class="at-sep row">
    <div class="col s1 offset-s5">
      <strong>{{sepText}}</strong>
    </div>
  </div>
</template>
```

to:

```
<template name="atSep">
  <div class="at-sep row">
    <div class="col s6 offset-s3 center-align">
      <strong>{{sepText}}</strong>
    </div>
  </div>
</template>
```

I forked the boilerplate but the issue is in the package itself...I'm not personally sure how to override static HTML output from a package. Hope my explanation and solution above is enough to get this problem resolved. I'd love to make the change myself but not sure how that works (I am a new Github user, sorry!)

Thanks for the speedy reply! Let me know if there's anything else I can do.

Note: just want to specify that the center-align class I used is the helper class from materialize.

**Comment by Sivli-Embir** [comment]
No worries, I made the change the above PR. @splendido I will let you review, I have not looked it over myself yet.

**Comment by Sivli-Embir** [comment]
@adamsidiali You can git clone this: https://github.com/meteor-useraccounts/materialize.git to see the change. Also if your still _very_ new to git you should checkout https://try.github.io.

**Comment by asidiali** [comment]
@Kestanous thanks very much for your help, I really appreciate it.
