### ISSUE TITLE
Cannot lock down client account creation

### ISSUE THREAD

**Issue by kylestew** [meteor-useraccounts/materialize#8]
It looks like including both `useraccounts:core` and `accounts-password` is causing the app to not boot when I try and lock client account creation on the server with the following:

```
Accounts.config({
  forbidClientAccountCreation: true
});
```

Is `accounts-password` necessary as a dependency? Removing it solves the issue. This is the error I see on startup:

W20150318-00:09:02.831(-7)? (STDERR) Error: Can't set `forbidClientAccountCreation` more than once
W20150318-00:09:02.831(-7)? (STDERR)     at packages/accounts-base/accounts_common.js:95:1
W20150318-00:09:02.831(-7)? (STDERR)     at Array.forEach (native)
W20150318-00:09:02.831(-7)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
W20150318-00:09:02.831(-7)? (STDERR)     at Object.Accounts.config (packages/accounts-base/accounts_common.js:92:1)
W20150318-00:09:02.832(-7)? (STDERR)     at app/server/_config.js:2:10
W20150318-00:09:02.832(-7)? (STDERR)     at app/server/_config.js:6:3
W20150318-00:09:02.832(-7)? (STDERR)     at /Users/kyle/Projects/Create/meteor/.meteor/local/build/programs/server/boot.js:222:10
W20150318-00:09:02.832(-7)? (STDERR)     at Array.forEach (native)
W20150318-00:09:02.832(-7)? (STDERR)     at Function._.each._.forEach (/Users/kyle/.meteor/packages/meteor-tool/.1.0.42.1c3e8tu++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150318-00:09:02.832(-7)? (STDERR)     at /Users/kyle/Projects/Create/meteor/.meteor/local/build/programs/server/boot.js:117:5

**Comment by splendido** [comment]
Hi @kylestew!

Please refer to the useraccounts configuration and use:

``` javascript
AccountsTemplates.configure({
    forbidClientAccountCreation: true,
});
```

Lets see the [configuration options](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#options) section on the [Guide](https://github.com/meteor-useraccounts/core/blob/master/Guide.md)

The _normal_ solution you're trying to use cannot be used because useraccounts sets `Accounts.config({forbidClientAccountCreation: true});` by default to use its own user creation method.

**Comment by kylestew** [comment]
Thanks, was pulling my hair out trying to figure this one out

**Comment by splendido** [comment]
you're welcome!
